### ISSUE TITLE
怎么限制速度

### ISSUE THREAD

**Issue by shuyabin** [crabkun/crab#1]
你好大佬,想咨询一下,如果我想限制一下传输速度我应该从哪方面入手?

**Comment by crabkun** [comment]
你好，可以了解一下令牌桶算法(Token Bucket)，GO也有实现好的库可以使用
[https://github.com/juju/ratelimit](https://github.com/juju/ratelimit)

**Comment by shuyabin** [comment]
好的谢谢大佬
